name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *'  # 每一小时 **12** 小时同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/<ish2018>/<PG>.git
          git fetch upstream
          git reset --hard upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
